### ISSUE TITLE
Seamless looping

### ISSUE THREAD

**Issue by cskonopka** [TinyCircuits/TinyCircuits-TinyScreenPlus-ASM2022#1]
Is it possible to play a video as a seamless loop using this platform?

**Comment by TinyCircuits** [comment]
It is possible! 

There is an example sketch that loops video in order from an SD Card as soon as the TinyScreen+ is turned on. This is mostly used with the Tiny Video Player Kit (the TinyScreen+, and a MicroSD Card TinyShield) but if you have similar hardware, it can almost definitely be adapted. The Learn Page that includes the program is here: https://learn.tinycircuits.com/Kits/Tiny-Video-Player-Kit_Tutorial/

Or you can download it straight from the repository for that page. https://github.com/TinyCircuits/Wiki-Tutorials-Supporting-Files/tree/master/Kits/Tiny-Video-Player-Kit/software
